"use client";

import { BookOpen, BrainCircuit, Calculator, FileText, Image as ImageIcon, Paperclip, Send, Sparkles } from "lucide-react";
import { useState } from "react";

export default function AiTutorPage() {
  const [message, setMessage] = useState("");
  const [messages, setMessages] = useState<string[]>([]);
  const send = () => { if (!message.trim()) return; setMessages((items) => [...items, message]); setMessage(""); };
  return <main className="page tutor-page"><header className="page-header split-header tutor-header"><div><span className="eyebrow">YOUR STUDY PARTNER</span><h1><Sparkles /> AI Tutor</h1><p>Course-aware guidance, mocked for Milestone 1.</p></div><select aria-label="Tutor mode"><option>Tutor mode</option><option>Practice</option><option>Explain</option><option>Quiz Me</option><option>Exam Prep</option></select></header><div className="tutor-layout"><section className="panel chat-panel"><div className="message user-message"><span className="avatar">J</span><div><strong>You</strong><p>Can you explain Bernoulli’s equation in simple terms and show an example like the ones in Fluid Mechanics?</p></div></div><div className="message ai-message"><span className="ai-avatar"><Sparkles /></span><div><strong>AXIOM</strong><p>Bernoulli’s equation connects pressure, velocity and elevation along a streamline. If elevation stays constant, faster-moving fluid has lower static pressure.</p><div className="formula-display">P₁/ρg + V₁²/2g + z₁ = P₂/ρg + V₂²/2g + z₂</div><h3>Example approach</h3><ol><li>Use continuity to find the velocity at section 2.</li><li>Cancel equal elevation terms.</li><li>Rearrange Bernoulli’s equation for the unknown pressure.</li></ol></div></div>{messages.map((item, index) => <div className="message user-message" key={index}><span className="avatar">J</span><div><strong>You</strong><p>{item}</p></div></div>)}<div className="chat-compose"><button aria-label="Attach file"><Paperclip size={18} /></button><input value={message} onChange={(event) => setMessage(event.target.value)} onKeyDown={(event) => event.key === "Enter" && send()} placeholder="Ask Axiom anything..." /><button className="send-button" onClick={send} aria-label="Send"><Send size={18} /></button></div></section><aside className="tutor-side"><section className="panel side-card"><span className="eyebrow">COURSE CONTEXT</span><h3>MEE3003 — Fluid Mechanics</h3><p>3 mock files connected</p></section><section className="panel side-card"><strong>Study tools</strong><div className="tool-grid">{[[BookOpen, "Explain concept"], [Calculator, "Solve problem"], [FileText, "Summarize notes"], [BrainCircuit, "Generate questions"], [ImageIcon, "Draw diagram"]].map(([Icon, label]) => { const ToolIcon = Icon as typeof BookOpen; return <button key={label as string}><ToolIcon size={17} />{label as string}</button>; })}</div></section><section className="panel side-card"><strong>Suggested prompts</strong>{["Explain Reynolds number", "Quiz me on Topic 3", "Summarize Lecture 4"].map((prompt) => <button className="prompt-chip" key={prompt} onClick={() => setMessage(prompt)}>{prompt}</button>)}</section></aside></div></main>;
}
